export const ErrorCode = {
  // 인증
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  // 유저
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_NICKNAME: 'DUPLICATE_NICKNAME',
  // 팔로우
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',
  // 게시물
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  NOT_POST_OWNER: 'NOT_POST_OWNER',
  // 댓글
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  NOT_COMMENT_OWNER: 'NOT_COMMENT_OWNER',
  // 피팅
  FITTING_NOT_FOUND: 'FITTING_NOT_FOUND',
  FITTING_IN_PROGRESS: 'FITTING_IN_PROGRESS',
  FITTING_FAILED: 'FITTING_FAILED',
  // 옷장
  CLOSET_ITEM_NOT_FOUND: 'CLOSET_ITEM_NOT_FOUND',
  ALREADY_IN_CLOSET: 'ALREADY_IN_CLOSET',
  // 외부 API
  MESHY_API_ERROR: 'MESHY_API_ERROR',
  GEMINI_API_ERROR: 'GEMINI_API_ERROR',
  // 파일
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  // 공통
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
